Code done by Mourad Ali

Code reviewed by Tara Khobiary and Bora Yavuz

*   Distribution of Tumor Size Check: Completed
*   Categorical Distribution of A Stage Check: Completed
*   Survival Months Outliers Tested: Completed

Code Leveraged from Code Reuse Session 1,Block 1

In [ ]:
#I imported a suitable Python library to load and access my dataset
import pandas as pd

Code Leveraged from Code Reuse Session 1,Block 2

In [ ]:
#I used a suitable function to load my coursework dataset file
data = pd.read_csv('/content/5DATA002W.2 Coursework Dataset(25012025v6.0).csv')

Code Leveraged from Code Reuse Session 1,Block 3

In [ ]:
# I then used a method to display the first 10 recorded patients values per data
data.head(10)

,Patient_ID,Month_of_Birth,Age,Sex,Occupation,T_Stage,N_Stage,6th_Stage,Differentiated,Grade,A_Stage,Tumor_Size,Estrogen_Status,Progesterone_Status,Regional_Node_Examined,Reginol_Node_Positive,Survival_Months,Mortality_Status
0,A0012,12,68.0,Female,Teaching,T1,N1,IIA,Poorly differentiated,3,Regional,4.0,Positive,Positive,24.0,1,60,Alive
1,A0013,12,50.0,Female,Medical,T2,N2,IIIA,Moderately differentiated,2,Regional,35.0,Positive,Positive,14.0,5,62,Alive
2,A0014,11,58.0,Female,Engineering,T3,N3,IIIC,Moderately differentiated,2,Regional,63.0,Positive,Positive,14.0,7,75,Alive
3,A0015,3,58.0,Female,Technology,T1,N1,IIA,Poorly differentiated,3,Regional,18.0,Positive,Positive,2.0,1,84,Alive
4,A0016,1,47.0,Female,Multimedia,T2,N1,IIB,Poorly differentiated,3,Regional,41.0,Positive,Positive,3.0,1,50,Alive
5,A0017,2,51.0,Female,Research,T1,N1,IIA,Moderately differentiated,2,Regional,20.0,Positive,Positive,18.0,2,89,Alive
6,A0018,5,51.0,Female,House Person,T1,N1,IIA,Well differentiated,1,Regional,8.0,Positive,Positive,11.0,1,54,Alive
7,A0019,4,40.0,Female,Reporting,T2,N1,IIB,Moderately differentiated,2,Regional,30.0,Positive,Positive,9.0,1,14,Dead
8,A0020,6,40.0,Female,Development,T4,N3,IIIC,Poorly differentiated,3,Regional,103.0,Positive,Positive,20.0,18,70,Alive
9,A0021,4,69.0,Female,Construction,T4,N3,IIIC,Well differentiated,1,Distant,32.0,Positive,Positive,21.0,12,92,Alive

Code Leveraged from Code Reuse Session 1,Block 4

In [ ]:
#I listed the variable names in the dataset
list(data.columns)

['Patient_ID',
 'Month_of_Birth',
 'Age',
 'Sex',
 'Occupation',
 'T_Stage',
 'N_Stage',
 '6th_Stage',
 'Differentiated',
 'Grade',
 'A_Stage',
 'Tumor_Size',
 'Estrogen_Status',
 'Progesterone_Status',
 'Regional_Node_Examined',
 'Reginol_Node_Positive',
 'Survival_Months',
 'Mortality_Status']

Code Leveraged from seminar week 2, block 15 and Code Reuse Session 1,Block 4

In [ ]:
#Correcting the spelling for the variable Reginol_Node_Positive
data.rename({'Reginol_Node_Positive':"Regional_Node_Positive"}, axis=1, inplace=True)
list(data.columns)

['Patient_ID',
 'Month_of_Birth',
 'Age',
 'Sex',
 'Occupation',
 'T_Stage',
 'N_Stage',
 '6th_Stage',
 'Differentiated',
 'Grade',
 'A_Stage',
 'Tumor_Size',
 'Estrogen_Status',
 'Progesterone_Status',
 'Regional_Node_Examined',
 'Regional_Node_Positive',
 'Survival_Months',
 'Mortality_Status']

Code Leveraged from Code Reuse Session 1,Block 5

In [ ]:
#With this function i am able to view all the data types per variable in the dataset
#I will also be able to view the variables with missing entries
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Patient_ID              4024 non-null   object
 1   Month_of_Birth          4024 non-null   int64
 2   Age                     4015 non-null   float64
 3   Sex                     4020 non-null   object
 4   Occupation              43 non-null     object
 5   T_Stage                 4024 non-null   object
 6   N_Stage                 4024 non-null   object
 7   6th_Stage               4024 non-null   object
 8   Differentiated          4024 non-null   object
 9   Grade                   4024 non-null   int64
 10  A_Stage                 4024 non-null   object
 11  Tumor_Size              4021 non-null   float64
 12  Estrogen_Status         4024 non-null   object
 13  Progesterone_Status     4024 non-null   object
 14  Regional_Node_Examined  4023 non-null   float64
 15  Regional_Node_Positive  4024 non-null   int64
 16  Survival_Months         4024 non-null   int64
 17  Mortality_Status        4024 non-null   object
dtypes: float64(3), int64(4), object(11)
memory usage: 566.0+ KB

Code Leveraged from Code Reuse Session 1,Block 6

In [ ]:
#This method only calculates and displays the dimensions of my dataset
data.shape

(4024, 18)

Code Leveraged from Code Reuse Session 1,Block 7

In [ ]:
#This method allows me to investigate any issues in your cancer patients’ data by displaying the basic descriptive statistics for the numeric variables only in the dataset
data.describe()

       Month_of_Birth          Age        Grade   Tumor_Size  Regional_Node_Examined  Regional_Node_Positive  Survival_Months
count     4024.000000  4015.000000  4024.000000  4021.000000             4023.000000             4024.000000      4024.000000
mean         6.481362    54.107098     2.150596    30.419299               14.373602                4.158052        71.472167
std          3.475442    11.715528     0.638234    21.161080                8.129293                5.109331        25.361855
min          1.000000   -50.000000     1.000000   -75.000000                1.000000                1.000000         1.000000
25%          3.000000    47.000000     2.000000    16.000000                9.000000                1.000000        56.000000
50%          6.000000    54.000000     2.000000    25.000000               14.000000                2.000000        73.000000
75%         10.000000    61.000000     3.000000    38.000000               19.000000                5.000000        90.000000
max         12.000000   502.000000     4.000000   140.000000               61.000000               46.000000       760.000000

Code Leveraged from Code Reuse Session 1,Block 8

In [ ]:
#I used a method to investigate any issues in your cancer patients’ data by displaying the basic descriptive statistics for the categorical variables only in the dataset
data.describe(include='object')

,Patient_ID,Sex,Occupation,T_Stage,N_Stage,6th_Stage,Differentiated,A_Stage,Estrogen_Status,Progesterone_Status,Mortality_Status
count,4024,4020,43,4024,4024,4024,4024,4024,4024,4024,4024
unique,4024,2,40,4,3,5,4,2,2,2,7
top,A4035,Female,House Person,T2,N1,IIA,Moderately differentiated,Regional,Positive,Positive,Alive
freq,1,4001,2,1786,2732,1305,2351,3932,3755,3326,3399

Code Leveraged from Code Reuse Session 1,Block 9

In [ ]:
#this allows me to explore my dataset, and uses a method that shows the distinct values for my variables
data['Differentiated'].unique()

array(['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'], dtype=object)

Code Leveraged from Code Reuse Session 1,Block 9

In [ ]:
#this allows me to explore my dataset, and uses a method that shows the distinct values for my variables
#With this code it shows that there is no varience with the column therefore it will be dropped
data['Sex'].unique()

array(['Female', '1', nan], dtype=object)

Code Leveraged from Code Reuse Session 1,Block 12

In [ ]:
#I have deemed these two variables unnecessary hence they were removed
data = data.drop(columns=(['Occupation' ,'Patient_ID' ,'Month_of_Birth', 'Sex']))

Code Leveraged from Code Reuse Session 1,Block 10

In [ ]:
#i am able to view the count of patients who have missing values per variable
data.isnull().sum()

Age                       9
T_Stage                   0
N_Stage                   0
6th_Stage                 0
Differentiated            0
Grade                     0
A_Stage                   0
Tumor_Size                3
Estrogen_Status           0
Progesterone_Status       0
Regional_Node_Examined    1
Regional_Node_Positive    0
Survival_Months           0
Mortality_Status          0
dtype: int64

Code Leveraged from Code Reuse Session 1,Block 11

In [ ]:
#This block of code calculates and displays the portion (percentage) of patients with missing values per variable
data.isna().sum()/len(data)*100

Age                       0.223658
T_Stage                   0.000000
N_Stage                   0.000000
6th_Stage                 0.000000
Differentiated            0.000000
Grade                     0.000000
A_Stage                   0.000000
Tumor_Size                0.074553
Estrogen_Status           0.000000
Progesterone_Status       0.000000
Regional_Node_Examined    0.024851
Regional_Node_Positive    0.000000
Survival_Months           0.000000
Mortality_Status          0.000000
dtype: float64

Code Leveraged from Code Reuse Session 1,Block 13

In [ ]:
#I imported a Python package to visualise my variables
import plotly.express as px

Code Leveraged from Code Reuse Session 1,Block 14

In [ ]:
#I used a univariate visualisation method to show the frequency distribution of Tumor_Size
VariableName_fig = px.histogram(data, x='Tumor_Size')

VariableName_fig.show()

Code Leveraged from Code Reuse Session 1,Block 15

In [ ]:
#I used a univariate visualisation method to show the categorical variable of A_Stage
VariableName_fig = px.bar(data, x='A_Stage')

VariableName_fig.show()

Code Leveraged from Code Reuse Session 1,Block 15

In [ ]:
#I used a univariate visualisation method to show the categorical variable of A_Stage
VariableName_fig = px.bar(data, x='Mortality_Status')

VariableName_fig.show()

Code Leveraged from Code Reuse Session 1,Block 16

In [ ]:
#I used a univariate visualisation method to test my patients data with an IQR of 1.75 for the variable age
VariableName_fig = px.box(data, x='Age')

VariableName_fig.show()

Code Leveraged from Code Reuse Session 1,Block 17

In [ ]:
#I built a function that detects outliers in any variable of my choice based on the interquartile range
def find_outliers_IQR(data):

  q1=data.quantile(0.25)

  q3=data.quantile(0.75)

  IQR=q3-q1

  outliers = data[((data<(q1-1.75*IQR))|(data>(q3+1.75*IQR)))]

  return outliers

Code Leveraged from Code Reuse Session 1,Block 19

In [ ]:
#I called my built function to display the detected outliers in my chosen variables (Survival_Months, Age and Tumor_Size).
outliers = find_outliers_IQR(data['Survival_Months'])

print("number of outliers: "+ str(len(outliers)))

outliers

number of outliers: 1

374    760
Name: Survival_Months, dtype: int64

Code Leveraged from Code Reuse Session 1,Block 19

In [ ]:
##I called my built function to display the detected outliers in my chosen variables (Survival_Months, Age and Tumor_Size).
outliers = find_outliers_IQR(data['Age'])

print("number of outliers: "+ str(len(outliers)))

outliers

number of outliers: 4

142    180.0
212    -50.0
522    502.0
842     89.0
Name: Age, dtype: float64

Code Leveraged from Code Reuse Session 1,Block 18

In [ ]:
#I used a method to control the rows and columns truncation in my dataset as Pandas truncates the displayed data for larger datasets by defult.
pd.set_option('display.max_rows', 500)

pd.set_option('display.max_columns', 500)

pd.set_option('display.width', 150)

Code Leveraged from Code Reuse Session 1,Block 20

In [ ]:
#I used the index of the detected outlier patients in a method to remove them from my dataset.
data.drop(data.index[[374, 142, 212, 522]], inplace=True)

Code Leveraged from Code Reuse Session 1,Block 19

In [ ]:
#I am perfroming this code to do a check that the selected outliers were removed
outliers = find_outliers_IQR(data['Age'])

print("number of outliers: "+ str(len(outliers)))

outliers

number of outliers: 1

842    89.0
Name: Age, dtype: float64

Code Leveraged from Code Reuse Session 1,Block 19

In [ ]:
#I am perfroming this code to do a check that the selected outliers were removed

outliers = find_outliers_IQR(data['Survival_Months'])

print("number of outliers: "+ str(len(outliers)))

outliers

number of outliers: 0

Series([], Name: Survival_Months, dtype: int64)

Code Leveraged from Code Reuse Session 1,Block 21

In [ ]:
#I filled out the missing variables entries with the mean
Mean_Age = data['Age'].mean()
Mean_Tumor_Size = data['Tumor_Size'].mean()
Mean_Regional_Node_Examined = data['Regional_Node_Examined'].mean()

data['Age'].fillna(Mean_Age, inplace=True)
data['Tumor_Size'].fillna(Mean_Tumor_Size, inplace=True)
data['Regional_Node_Examined'].fillna(Mean_Regional_Node_Examined, inplace=True)

<ipython-input-301-69ee7b9e6197>:6: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



<ipython-input-301-69ee7b9e6197>:7: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



<ipython-input-301-69ee7b9e6197>:8: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

Code Leveraged from Code Reuse Session 1,Block 3

In [ ]:
# I then used a method to display the first 10 recorded patients values per data to perform a before check on the encoding of the categorical variables
data.head(10)

,Age,T_Stage,N_Stage,6th_Stage,Differentiated,Grade,A_Stage,Tumor_Size,Estrogen_Status,Progesterone_Status,Regional_Node_Examined,Regional_Node_Positive,Survival_Months,Mortality_Status
0,68.0,T1,N1,IIA,Poorly differentiated,3,Regional,4.0,Positive,Positive,24.0,1,60,Alive
1,50.0,T2,N2,IIIA,Moderately differentiated,2,Regional,35.0,Positive,Positive,14.0,5,62,Alive
2,58.0,T3,N3,IIIC,Moderately differentiated,2,Regional,63.0,Positive,Positive,14.0,7,75,Alive
3,58.0,T1,N1,IIA,Poorly differentiated,3,Regional,18.0,Positive,Positive,2.0,1,84,Alive
4,47.0,T2,N1,IIB,Poorly differentiated,3,Regional,41.0,Positive,Positive,3.0,1,50,Alive
5,51.0,T1,N1,IIA,Moderately differentiated,2,Regional,20.0,Positive,Positive,18.0,2,89,Alive
6,51.0,T1,N1,IIA,Well differentiated,1,Regional,8.0,Positive,Positive,11.0,1,54,Alive
7,40.0,T2,N1,IIB,Moderately differentiated,2,Regional,30.0,Positive,Positive,9.0,1,14,Dead
8,40.0,T4,N3,IIIC,Poorly differentiated,3,Regional,103.0,Positive,Positive,20.0,18,70,Alive
9,69.0,T4,N3,IIIC,Well differentiated,1,Distant,32.0,Positive,Positive,21.0,12,92,Alive

Code Leveraged from Code Reuse Session 1,Block 23

In [ ]:
#I used a method to map the binary categorical values of 'Mortality_Status' to numeric codes
data['Mortality_Status'] = data['Mortality_Status'].map({'Alive': 1, 'ALIVE': 1, 'ALive': 1, 'alive': 1, 'Dead': 0,'DEAD': 0, 'dead': 0})

Code Leveraged from Code Reuse Session 1,Block 24

In [ ]:
data = data.astype({"Age":"int"})

Code Leveraged from Code Reuse Session 1,Block 25

In [ ]:
#I imported a preprocessing library from Sklearn to encode an ordinal column to labels
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

Code Leveraged from Code Reuse Session 1,Block 26

In [ ]:
#I decided to encode an object type variable whose values are ordinal and applied the function to 'Differentiated', 'T_Stage', 'N_Stage', '6th_Stage', 'A_Stage', 'Estrogen_Status', 'Progesterone_Status'
label_encoder = preprocessing.LabelEncoder()

data['Differentiated']= label_encoder.fit_transform(data['Differentiated'])

data['T_Stage']= label_encoder.fit_transform(data['T_Stage'])

data['N_Stage']= label_encoder.fit_transform(data['N_Stage'])

data['6th_Stage']= label_encoder.fit_transform(data['6th_Stage'])

data['A_Stage']= label_encoder.fit_transform(data['A_Stage'])

data['Estrogen_Status']= label_encoder.fit_transform(data['Estrogen_Status'])

data['Progesterone_Status']= label_encoder.fit_transform(data['Progesterone_Status'])

Code Leveraged from Code Reuse Session 1,Block 3

In [ ]:
# I then used a method to display the first 10 recorded patients values per data to perform a after check on the encoding of the categorical variables
data.head(10)

,Age,T_Stage,N_Stage,6th_Stage,Differentiated,Grade,A_Stage,Tumor_Size,Estrogen_Status,Progesterone_Status,Regional_Node_Examined,Regional_Node_Positive,Survival_Months,Mortality_Status
0,68,0,0,0,1,3,1,4.0,1,1,24.0,1,60,1
1,50,1,1,2,0,2,1,35.0,1,1,14.0,5,62,1
2,58,2,2,4,0,2,1,63.0,1,1,14.0,7,75,1
3,58,0,0,0,1,3,1,18.0,1,1,2.0,1,84,1
4,47,1,0,1,1,3,1,41.0,1,1,3.0,1,50,1
5,51,0,0,0,0,2,1,20.0,1,1,18.0,2,89,1
6,51,0,0,0,3,1,1,8.0,1,1,11.0,1,54,1
7,40,1,0,1,0,2,1,30.0,1,1,9.0,1,14,0
8,40,3,2,4,1,3,1,103.0,1,1,20.0,18,70,1
9,69,3,2,4,3,1,0,32.0,1,1,21.0,12,92,1

Code Leveraged from Code Reuse Session 1,Block 5

In [ ]:
#With this function i am able to view all the data types per variable in the dataset
#I will also be able to view the variables with missing entries
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4020 entries, 0 to 4023
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4020 non-null   int64
 1   T_Stage                 4020 non-null   int64
 2   N_Stage                 4020 non-null   int64
 3   6th_Stage               4020 non-null   int64
 4   Differentiated          4020 non-null   int64
 5   Grade                   4020 non-null   int64
 6   A_Stage                 4020 non-null   int64
 7   Tumor_Size              4020 non-null   float64
 8   Estrogen_Status         4020 non-null   int64
 9   Progesterone_Status     4020 non-null   int64
 10  Regional_Node_Examined  4020 non-null   float64
 11  Regional_Node_Positive  4020 non-null   int64
 12  Survival_Months         4020 non-null   int64
 13  Mortality_Status        4020 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 471.1 KB

Code Leveraged from Code Reuse Session 1,Block 6

In [ ]:
#This method only calculates and displays the dimensions of my dataset
data.shape

(4020, 14)

Code Leveraged from Code Reuse Session 1,Block 27

In [ ]:
#I saved my cleaned dataset to a csv format file
data.to_csv(r'/content/5DATA002W.2 Coursework Dataset(cleaned).csv', index=False)

Code Leveraged from Code Reuse Session 1,Block 28

In [ ]:
#I used a filtering method to isolate all patients whose mortality status is dead
filtered_data = data[data.Mortality_Status < 1]

Code Leveraged from Code Reuse Session 1,Block 5

In [ ]:
#With this function i am able to view all the data types per variable in the dataset
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 615 entries, 7 to 4017
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     615 non-null    int64
 1   T_Stage                 615 non-null    int64
 2   N_Stage                 615 non-null    int64
 3   6th_Stage               615 non-null    int64
 4   Differentiated          615 non-null    int64
 5   Grade                   615 non-null    int64
 6   A_Stage                 615 non-null    int64
 7   Tumor_Size              615 non-null    float64
 8   Estrogen_Status         615 non-null    int64
 9   Progesterone_Status     615 non-null    int64
 10  Regional_Node_Examined  615 non-null    float64
 11  Regional_Node_Positive  615 non-null    int64
 12  Survival_Months         615 non-null    int64
 13  Mortality_Status        615 non-null    int64
dtypes: float64(2), int64(12)
memory usage: 72.1 KB

Code Leveraged from Code Reuse Session 1,Block 6

In [ ]:
#This method only calculates and displays the dimensions of my dataset
filtered_data.shape

(615, 14)

Code Leveraged from Code Reuse Session 1,Block 27

In [ ]:
#I saved my cleaned dataset to a csv format file
filtered_data.to_csv(r'/content/5DATA002W.2 Coursework Dataset(filtered).csv', index=False)